package com.bhnetwork.integration.pppstodax.canonical;

public class Product {
	// from DAX
	private String ItemGroupId
	private String ItemId
	private String ItemName
	private String ItemType
	private String ItemPriceToleranceGroupId
	private String Dimension
	private String Dimension[Product]
	private String NameAlias
	private String DimGroupId
	private String ModelGroupId
	private String ItemBuyerGroupId
	private String bhnCheckDigit
	private String jsSearchText
	private String bhnIsEANUPC
	private String bhnSubGroup
	private String bhnDivision
	private String bhnCompany
	private String bhnComplete
	private String bhnNotes
	private String bhnStatus
	private String bhnSetupCompletedBy
	private String bhnSetupCompleteDate
	private String bhnBarcodeType
	private String bhnGUID
	private String dataAreaId
	private String Currency
	private String IssuerCompanyCode
	private String MulticardIndicator
	private String ProductType
	private String ServiceProvider
	private String VariableIndicator
	private String ReasonCode
	private String OwnershipType
	private String Denomination
	private String ProductClass
	private String ProductGroup
	private String bhnVariableMin
	private String bhnVariableMax
	private String TaxIncluded
	private String ProcessorType
	private String CheckMinMax
	private String modifiedDateTime
	private String modifiedBy
	private String createdDateTime
	private String createdBy
	private String recVersion
	private String RecId
	// from 3PS
	private String productTypeID
	private String productInventorySource
	private String productUseStandardDesignTemplate
}
